-- 발주(SalesOrder) 애그리거트. 상태 변경 부가 데이터는 sales_order_status_history로 분리(평탄화 컬럼 없음).
-- 창고명·행위자 name/position은 확정 시점 스냅샷(DRAFT는 code만 → nullable).
CREATE TABLE sales_orders (
    code                   VARCHAR(255) NOT NULL,
    from_warehouse_code    VARCHAR(255) NOT NULL,
    to_warehouse_code      VARCHAR(255) NOT NULL,
    status                 VARCHAR(255) NOT NULL,
    request_memo           TEXT,
    -- 낙관락 버전
    version                BIGINT       NOT NULL DEFAULT 0,
    -- 비동기 재고 saga 진행 상태(transport 관심사). 비즈니스 status와 분리.
    saga_status            VARCHAR(255) NOT NULL DEFAULT 'NONE',
    -- saga 실패 사유(진행 폴링 응답에 노출)
    last_failure_reason    TEXT,
    -- creation (운영 컬럼: 목록·정렬·검증)
    created_by             VARCHAR(255),
    created_by_name        VARCHAR(255),
    created_by_position    VARCHAR(255),
    created_at             TIMESTAMP(6) WITH TIME ZONE,
    -- request
    requested_by           VARCHAR(255),
    requested_by_name      VARCHAR(255),
    requested_by_position  VARCHAR(255),
    requested_at           TIMESTAMP(6) WITH TIME ZONE,
    -- 창고명 스냅샷(확정 시점 박제)
    from_warehouse_name    VARCHAR(255),
    to_warehouse_name      VARCHAR(255),
    CONSTRAINT pk_sales_orders PRIMARY KEY (code)
);

-- 지점 목록: from_warehouse_code 필터 + requested_at 정렬/범위
CREATE INDEX idx_so_from_warehouse_requested_at ON sales_orders (from_warehouse_code, requested_at);
-- 본사 목록: 창고 미지정 시 requested_at 범위/정렬
CREATE INDEX idx_so_requested_at ON sales_orders (requested_at);
-- 상태 집계(KPI)·status IN 필터
CREATE INDEX idx_so_status ON sales_orders (status);

-- 발주 라인. so_code FK로 sales_orders 참조.
CREATE TABLE sales_order_lines (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    so_code             VARCHAR(255) NOT NULL,
    item_code           VARCHAR(255) NOT NULL,
    item_name_snapshot  VARCHAR(255),
    unit_snapshot       VARCHAR(255),
    quantity            INTEGER      NOT NULL,
    priority            VARCHAR(255) NOT NULL,
    CONSTRAINT pk_sales_order_lines PRIMARY KEY (id),
    CONSTRAINT fk_sales_order_lines_so_code FOREIGN KEY (so_code) REFERENCES sales_orders (code)
);

-- 라인 묶음 조회(@Formula itemCount·EXISTS 검색·라인 로드)
CREATE INDEX idx_sol_so_code ON sales_order_lines (so_code);

-- SO 코드 월별 채번 시퀀스. INSERT ... ON CONFLICT DO UPDATE ... RETURNING 원자적 upsert로 증가.
CREATE TABLE so_number_sequences (
    seq_date DATE    NOT NULL,
    last_seq INTEGER NOT NULL,
    CONSTRAINT pk_so_number_sequences PRIMARY KEY (seq_date)
);

-- 발주 상태 변경 이력. SalesOrder와 FK·연관관계 없음(decoupled, append-only audit log).
-- 상태별 부가 데이터는 payload(jsonb)에 보관. actor(사번·name·position)·status·created_at은 공통 컬럼.
CREATE TABLE sales_order_status_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    so_code        VARCHAR(255)             NOT NULL,
    status         VARCHAR(255)             NOT NULL,
    actor_code     VARCHAR(255)             NOT NULL,
    actor_name     VARCHAR(255),
    actor_position VARCHAR(255),
    payload        JSONB,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_sales_order_status_history PRIMARY KEY (id)
);

-- 이력 조회: so_code 단건 + created_at 최신순 정렬.
CREATE INDEX idx_so_status_history_so_code_created_at
    ON sales_order_status_history (so_code, created_at DESC);
-- 이력 조회: so_code + status 필터 + created_at 최신순(특정 상태 최신 행 조회).
CREATE INDEX idx_so_status_history_so_code_status_created_at
    ON sales_order_status_history (so_code, status, created_at DESC);

-- 트랜잭셔널 outbox. 비즈니스 변경과 같은 트랜잭션에 메시지를 적재해 발행 원자성을 보장한다.
-- payload는 직렬화된 BaseEvent envelope 전체(JSON 문자열).
CREATE TABLE outbox (
    event_id       UUID         NOT NULL,
    aggregate_id   VARCHAR(255) NOT NULL,
    event_type     VARCHAR(255) NOT NULL,
    payload        TEXT         NOT NULL,
    status         VARCHAR(255) NOT NULL,
    retry_count    INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    published_at   TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_outbox PRIMARY KEY (event_id)
);

-- 폴러가 미발행 행을 오래된 순으로 스캔한다.
CREATE INDEX idx_outbox_status_created_at ON outbox (status, created_at);

-- saga 확정 대기 상태 변경(staging). 발주당 1건이므로 so_code가 PK.
-- saga DONE 시 이력으로 승격 후 삭제, FAILED 시 삭제된다.
CREATE TABLE pending_status_change (
    so_code        VARCHAR(255)               NOT NULL,
    status         VARCHAR(255)               NOT NULL,
    actor_code     VARCHAR(255)               NOT NULL,
    actor_name     VARCHAR(255),
    actor_position VARCHAR(255),
    payload        JSONB,
    occurred_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_pending_status_change PRIMARY KEY (so_code)
);
