-- 발주(SalesOrder) 애그리거트. 이력 임베디드(creation/request/approval/rejection/delivery/cancellation)는 컬럼으로 평탄화.
CREATE TABLE sales_orders (
    code                   VARCHAR(255) NOT NULL,
    from_warehouse_code    VARCHAR(255) NOT NULL,
    to_warehouse_code      VARCHAR(255) NOT NULL,
    status                 VARCHAR(255) NOT NULL,
    desired_arrival_date   DATE         NOT NULL,
    request_memo           TEXT,
    -- creation
    created_by             VARCHAR(255),
    created_at             TIMESTAMP(6) WITH TIME ZONE,
    -- request
    requested_by           VARCHAR(255),
    requested_at           TIMESTAMP(6) WITH TIME ZONE,
    -- approval
    approved_by            VARCHAR(255),
    approved_at            TIMESTAMP(6) WITH TIME ZONE,
    approved_date          DATE,
    carrier_type           VARCHAR(255),
    invoice_number         VARCHAR(255),
    -- rejection
    rejected_by            VARCHAR(255),
    rejected_at            TIMESTAMP(6) WITH TIME ZONE,
    reject_reason_category VARCHAR(255),
    reject_reason_memo     VARCHAR(255),
    -- delivery
    delivered_by           VARCHAR(255),
    delivered_date         DATE,
    delivered_at           TIMESTAMP(6) WITH TIME ZONE,
    diff_reason_category   VARCHAR(255),
    diff_reason_memo       VARCHAR(255),
    -- cancellation
    canceled_by            VARCHAR(255),
    canceled_at            TIMESTAMP(6) WITH TIME ZONE,
    cancel_reason          VARCHAR(255),
    CONSTRAINT pk_sales_orders PRIMARY KEY (code),
    CONSTRAINT uq_sales_orders_invoice_number UNIQUE (invoice_number)
);

-- 발주 라인. so_code FK로 sales_orders 참조.
CREATE TABLE sales_order_lines (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    so_code             VARCHAR(255) NOT NULL,
    item_code           VARCHAR(255) NOT NULL,
    item_name_snapshot  VARCHAR(255),
    unit_snapshot       VARCHAR(255),
    requested_quantity  INTEGER      NOT NULL,
    approved_quantity   INTEGER,
    delivered_quantity  INTEGER,
    priority            VARCHAR(255) NOT NULL,
    CONSTRAINT pk_sales_order_lines PRIMARY KEY (id),
    CONSTRAINT fk_sales_order_lines_so_code FOREIGN KEY (so_code) REFERENCES sales_orders (code)
);

-- SO 코드 월별 채번 시퀀스. 비관적 락 대상.
CREATE TABLE so_number_sequences (
    seq_date DATE    NOT NULL,
    last_seq INTEGER NOT NULL,
    CONSTRAINT pk_so_number_sequences PRIMARY KEY (seq_date)
);
