-- 발주 상태 변경 이력. SalesOrder와 FK·연관관계 없음(decoupled, append-only audit log).
-- 상태별 부가 데이터는 payload(jsonb)에 보관. actor_code(사번)·status·created_at은 공통 컬럼.
CREATE TABLE sales_order_status_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    so_code    VARCHAR(255)             NOT NULL,
    status     VARCHAR(255)             NOT NULL,
    actor_code VARCHAR(255)             NOT NULL,
    payload    JSONB,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_sales_order_status_history PRIMARY KEY (id)
);

-- 이력 조회: so_code 단건 + created_at 최신순 정렬.
CREATE INDEX idx_so_status_history_so_code_created_at
    ON sales_order_status_history (so_code, created_at DESC);
